### ISSUE TITLE
Normalize use of "zeit"/"the zeit"/"Zeit"/"die Zeit"

### ISSUE THREAD

**Issue by SiC42** [dnkrsl/global_terror_analysis#12]

**Comment by dnkrsl** [comment]
the "Zeit" ?

**Comment by dnkrsl** [comment]
and the "Zeit"-newspaper

**Comment by SiC42** [comment]
Example: To get the needed information from Zeit, we filtered the articles by location.

**Comment by SiC42** [comment]
normalized everything to the Zeit
